# Generated by Django 4.0.1 on 2022-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hotel_hotelroom_remove_user_username_hotelroomtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('room_number', models.PositiveIntegerField()),
                ('qr_photo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hotelroomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
