# Generated by Django 4.0.1 on 2022-02-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_hotelcontact_hotel_remove_hotelphoto_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account',
            field=models.CharField(default='', max_length=200),
        ),
    ]
